name: Angular Packages
on:
  release:
    types: [created, edited]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Install Angular
        run: npm install -g @angular/cli@latest
      - name: Check Angular.
        run: ng version
      - name: Install Dependency. 
        run: npm ci
      - name: Run Build
        run: ng build --configuration=production
      - name: List Directory
        run: ls -a
      # - name: Change Working directory
      #   run:
      #     working-directory: ./dist/ng-safe-eval
      #   run: cd dist
      # - name: List Directory
      #   run: ls -a
      # - name: Change To Libary
      #   run: cd ng-safe-eval
     
      - name: View
        run: ls
      - name: Change Directory and Run
        working-directory: ./dist/ng-safe-eval
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Set up npm registry
        run: |
           echo "registry=https://registry.npmjs.org/" > .npmrc
           echo "//registry.npmjs.org/:_authToken=${{ secrets.TOKEN_NPM }}" >> .npmrc
      - name: User
        run: npm whoami
      - name: Install Angular
        run: npm install -g @angular/cli@latest
      - name: Check Angular.
        run: ng version
      - name: Install Dependency. 
        run: npm ci
      - name: Run Build
        run: ng build --configuration=production 
      - name: List Directory
        run: ls -a
      # - name: Change Working directory
      #   run: cd dist
      # - name: List Directory
      #   run: ls -a
      # - name: Change To Libary
      #   run: cd ng-safe-eval
     
      - name: View
        run: ls
      - name: Change Directory and Run
        working-directory: ./dist/ng-safe-eval
        run: npm publish --access=public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_NPM}}
