name: Angular Packages
on:
  release:
    types: [created, edited]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - run: npm install -g @angular/cli
  #     - run: npm ci

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Install Angular
        run: npm install -g @angular/cli@latest
      - name: Check Angular.
        run: ng version
      - name: Install Dependency. 
        run: npm i
      - name: Run Build
        run: ng build --configuration=production
      - name: List Directory
        run: ls -a
      # - name: Change Working directory
      #   run:
      #     working-directory: ./dist/ng-safe-eval
      #   run: cd dist
      # - name: List Directory
      #   run: ls -a
      # - name: Change To Libary
      #   run: cd ng-safe-eval
      - run: pwd
      - run: cd ./dist/ng-safe-eval && npm publish --access=public
        env:
          GIT_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install Angular
        run: npm install -g @angular/cli@latest
      - name: Check Angular.
        run: ng version
      - name: Install Dependency. 
        run: npm i
      - name: Run Build
        run: ng build --configuration=production 
      - name: List Directory
        run: ls -a
      # - name: Change Working directory
      #   run: cd dist
      # - name: List Directory
      #   run: ls -a
      # - name: Change To Libary
      #   run: cd ng-safe-eval
      - run: echo pwd
      - run: cd ./dist/ng-safe-eval && npm publish --access=public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_NPM}}
